gnuplot ./plot_average_cpu_time.gpl
gnuplot ./plot_average_frametime.gpl
gnuplot ./plot_batchcount_perf.gpl
gnuplot ./plot_batchsize_perf.gpl
gnuplot ./plot_cpu_performance.gpl
gnuplot ./plot_filter_efficiency.gpl
gnuplot ./plot_multitriangle_performance.gpl
gnuplot ./plot_performance.gpl
gnuplot ./plot_resolution_effect.gpl
gnuplot ./plot_visible_triangles.gpl
gnuplot ./plot_filter_histo.gpl.gpl
